GET http://localhost:3333/coursers?page=2

### 

POST http://localhost:3333/coursers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTk4YWFiMS0wOWU1LTc3N2QtYWZkMS0yMDE2NDBmYmUzODMiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTIxMzk3MCwiZXhwIjoxNzU1MzAwMzcwfQ.KNJpHbfj2Ee30myNao-FZqHknqsP2sCJVSapmHTHvyE

{
  "title": "Nuxt 5"
}

### 

GET http://localhost:3333/coursers/0198aada-4ad0-735c-a9f4-1c2f51c0d824
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTk4YWFiMS0wOWU1LTc3N2QtYWZkMS0yMDE2NDBmYmUzODMiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTIxMzk3MCwiZXhwIjoxNzU1MzAwMzcwfQ.KNJpHbfj2Ee30myNao-FZqHknqsP2sCJVSapmHTHvyE

### 

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Helio23@live.com",
  "password": "123456"
}