GET http://localhost:3333/coursers?page=2

### 

POST http://localhost:3333/coursers
Content-Type: application/json

{
  "title": "Nuxt 3"
}

### 

GET http://localhost:3333/coursers/0198a957-ebdf-704e-97ed-87a0973925b6

### 

PUT http://localhost:3333/coursers/4
Content-Type: application/json

{
  "title": "Updated Name"
}

###

DELETE http://localhost:3333/coursers/a0891813-7b00-4a81-a4b9-25b91404a986